version: '3.8'

services:
  # Redis Stack - includes RedisJSON and Streams
  redis:
    image: redis/redis-stack:7.2.0-v10
    container_name: keymanager-redis
    ports:
      - "6379:6379"
      - "18001:8001"  # RedisInsight
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
      - ./redis_users.acl:/data/users.acl
    command: redis-stack-server --save 60 1 --loglevel warning --aclfile /data/users.acl
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "default", "-a", "defaultpass", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # API Key Manager
  keymanager:
    build: .
    container_name: api-key-manager
    ports:
      - "12818:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: keymanager-network
